# 학습 이름(checkpoint, wandb 업로드명)
exp_name: 000 
# Seed
seed: 18
# Dice Threshold
threshold: 0.5
# Epoch 설정
epoch: 100

batch_size: 16
num_workers: 8
make_pickle: True

k-fold: False
fold: 3

defaults:
    - model: resnet101-fpn
    - optimizer: adam
    - scheduler: cosinewarmrestarts
    - augmentation: base