_target_: models.components.upernet_intern.UperNet
depths: [4, 4, 21, 4]
groups: [7, 14, 28, 56]
channels: 112
out_channels: [112, 224, 448, 896]
weights: https://huggingface.co/OpenGVLab/InternImage/resolve/main/internimage_b_1k_224.pth
